name: Build

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches:
    - main
    - features/*
  pull_request:
    branches: [ main ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Configure environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      # Build the project
      - name: Call build script
        run: ./build.sh

      # Prepare artifact(s)
      - run: cp ./LICENSE ./dist
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./dist/*
          retention-days: 30
